---
  - name: install common software
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - mc
      - python-setuptools
      - socat
    become: yes

  - easy_install:
      name: pip
    become: yes

  - name: Generate hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts
    become: yes    