---
  - name: Install needed dep 
    package:
      name:  "{{ item }}"
      state: present
    become: yes 
    with_items:
      - apt-transport-https
      - python-lxml
      - python-libvirt
      - libvirt-bin
      - qemu-kvm
      - libvirt-daemon-system
      - dnsmasq
    
  - name: start services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    become: yes
    with_items:
      - libvirtd
  
  
  - name: enable autostart for the default network
    virt_net:
      autostart: yes
      name: default
    become: yes 

  - name: start the default network
    virt_net:
      name: default
      state: active
    become: yes 

  - name: get kvm2 driver
    get_url:
      url: "https://github.com/kubernetes/minikube/releases/download/{{ minikube_version }}/docker-machine-driver-kvm2"
      dest: "{{ minikube_install_dir }}/docker-machine-driver-kvm2"
    become: yes 

  - name: chmod kvm driver
    file:
      dest: "{{ minikube_install_dir }}/docker-machine-driver-kvm2"
      mode: 0755  
    become: yes 