---
  myhosts:
    - { name: "dm", long_name: "dm.docker", ip: "192.168.101.10"}
    - { name: "km", long_name: "km.kubernetes", ip: "192.168.101.11"}

  app_name: "myapp"
  app_version: "v1"
  app_port: 3000
  app_replicas: 1



  minikube_install_dir: /usr/local/bin
  minikube_version: v0.25.2
  kubectl_version: v1.10.2
  docker_machine_version: v0.14.0
  docker_machine_xhyve_driver_version: v0.3.3

  #HELM
  kubernetes_helm_mirror: https://storage.googleapis.com/kubernetes-helm
  kubernetes_helm_ver: v2.8.1
  kubernetes_helm_platform: linux-amd64

  kubernetes_helm_bin_dir: /usr/local/bin

  kubernetes_helm_name: helm-{{kubernetes_helm_ver}}-{{kubernetes_helm_platform}}
  kubernetes_helm_tgz: '{{kubernetes_helm_name}}.tar.gz'

  kubernetes_helm_url: '{{kubernetes_helm_mirror}}/{{kubernetes_helm_tgz}}'
  kubernetes_helm_install_dir: '{{kubernetes_helm_bin_dir}}/helm-{{kubernetes_helm_ver}}'
  kubernetes_helm_checksum: '{{kubernetes_helm_checksums[kubernetes_helm_ver][kubernetes_helm_platform]}}'